### ISSUE TITLE
Add a description to the text file below explaining Inheritance in Java

### ISSUE THREAD

**Issue by cherryWood55** [cherryWood55/Inheritance-Concept#1]
https://github.com/cherryWood55/Inheritance-Concept/blob/master/Inheritance%20-%20The%20Concept

**Comment by Thuvan96** [comment]
Can i add information on inheritance

**Comment by cherryWood55** [comment]
Go ahead!

**Comment by Thuvan96** [comment]
am receiving an authentication failed message while trying to commit

**Comment by cherryWood55** [comment]
> 
> 
> am receiving an authentication failed message while trying to commit
I am sorry you did. What was the error?

**Comment by cherryWood55** [comment]
I am sorry you did. What was the error?

**Comment by Thuvan96** [comment]
![Capture](https://user-images.githubusercontent.com/42853486/66266577-864b1b00-e844-11e9-8012-3296e47345af.PNG)

**Comment by Thuvan96** [comment]
i am receiving this message
